### ISSUE TITLE
Query failed: java.net.UnknownHostException: hadoop

### ISSUE THREAD

**Issue by mikestnx** [parrot-stream/docker-hive#2]
Hi, 

I am running with docker-compose with no configuration changes in Kitematic and I am able to execute cmds such as SHOW SCHEMAS (via presto) but upon table creation I get the following exception:

Query xx__xx failed: java.net.UnknownHostException: hadoop

I don't actually see this hostname declared in the Hive config and I am not sure how docker-compose would setup local DNS/hostname lookup entries. 

Thanks!
Mike

**Comment by mcapitanio** [comment]
@mikestnx 
Hi!
If you look at the docker.compose.yml in Hive you'll notice that the hive service is linked to zookeeper, hadoop and postgred (for the Hive metadata) and all them are on the same network. This is enough to say docker that the "hive" service can contact the "hadoop" service using the hostname "hadoop". The hostname is equals to the service name in that case.

I don't know how would be in Kitematic, but if you just start hive with docker-compose you should get all services up and running and you would be able to use presto upon them.

**Comment by mikestnx** [comment]
Hi,

Yes I am running with docker-compose so KiteMatic is really just a UI to the regular Mac docker. Everything else is working it is just this hostname that is not resolvable it seems. I’ll keep trying. If docker-compose allows me to hardcode IPs I might be able to get it working like that.

Cheers,
Mike.

**Comment by mcapitanio** [comment]
Hi Mike,

to have Hive up and running you have to get also the services "hadoop", "zookeeper" and "postgres" (for the metastore) up and running.
The following docker-compose.yml should do the thing, because it sets th.e links dependecies and Docker do it all what is needed to define the hostaneme and set them in the dns for the "hadoop" network. I have written it without testing, but it should work.. .;)

```
version: '2'
services:
  postgres:
    image: mcapitanio/postgres:9.6
    networks:
    - hadoop
    ports:
    - 5432:5432
    environment: POSTGRES_PASSWORD:postgres
  zookeeper:
    image: mcapitanio/zookeeper:latest
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8086:8080
    networks:
    - hadoop
  hadoop:
    image: mcapitanio/hadoop:latest
    networks:
    - hadoop
    links:
    - zookeeper
    ports:
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
  hive:
    image: mcapitanio/hive:latest
    networks:
    - hadoop
    links:
    - hadoop
    - zookeeper
    - postgres
    environment:
      PGPASSWORD: postgres
    ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002
    - 10003:10003
    - 9083:9083
    - 50111:50111
    - 9999:9999
networks:
  hadoop:
    driver: bridge
```
